services:
- type: web
  name: glass-or-noglass-classifier_api
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "python flask_app.py"
  envVars:
  - key: FLASK_ENV
    value: production
  - key: PORT
    value: "5000"
